#!/bin/bash

# Copyright (C) 2017-2018 Andrei Pavel, andrei.pavel@cti.pub.ro
# Licensed under the MIT License

# Header
ARGUMENTS="\
  [-c|--confirm]               whether to ask user for confirmation
  -n \$count                    print \$count times
  [\$string]                    something other than \"Hello, world!\" to print
"
SCRIPT_PATH="$(dirname "$(readlink -f "${0}")")"
. "${SCRIPT_PATH}/lib/header"
. "${SCRIPT_PATH}/lib/utils"
. "${SCRIPT_PATH}/lib/spinner"
. "${SCRIPT_PATH}/lib/traps"

# Parse arguments.
while (( ${#} > 0 )); do
  case "${1}" in
  # [-c|--confirm]               whether to ask user for confirmation
  '-c'|'--confirm') confirm_required=true ;;
  # -n \$count                    print \$count times
  '-n') shift && count=${1} ;;
  *)
    # [\$string]                    something other than \"Hello, world!\" to print
    [[ -z "${string+x}" ]] && string="${1}" && shift && continue
    # Unrecognized argument
    printf "${RED}ERROR: Unrecognized argument '%s'${RESET}\\n" "${1}" 1>&2; print-usage; exit 1 ;;
  esac; shift
done

mandatory count

# Default arguments
[[ -z "${confirm_required+x}" ]] && confirm_required=false
[[ -z "${string+x}" ]] && string="Hello, world!"

#------------------------------------------------------------------------------#

start-spinner "Printing..."

if ${confirm_required} && ! confirm; then
  exit 0
fi

for (( i = 0; i < count; ++i )); do
  printf '%s\n' "${string}"
done

stop-spinner 0
