#!/bin/bash

# Copyright (C) 2017-2020 Andrei Pavel, andrei.pavel@mail.com
# Licensed under the MIT License

# Get script path and append it to PATH so other scripts are callable.
script_path="$(dirname "$(readlink -f "${0}")")"

# Header
. "${script_path}/lib/header"
. "${script_path}/lib/spinner"

parse-parameters "${@}"

#------------------------------------------------------------------------------#

start-spinner "Installing..."

find "${script_path}/lib" -mindepth 1 -maxdepth 1 -type f -exec basename {} \; | xargs -I{} bash -c "install -Dm644 '${script_path}/lib/{}' '/usr/local/bin/lib/{}'"

stop-spinner ${?}
