#!/bin/bash

# Copyright (C) 2017-2018 Andrei Pavel, andrei.pavel@cti.pub.ro
# Licensed under the MIT License

SUCCESS='DONE'
FAIL='FAIL'

_spinner_cycle='⠋⠙⠸⠴⠦⠇'
_spinner_period='0.15s'

function _display_message() {
  local status=${1}
  local mode=${2}
  if [[ ! -z ${status} && ${mode} != 'spinning' ]]; then
    status="[${status}]"
  fi
  printf "\\e[1A\\r%s%$(($(tput cols)-${#_message}-8))s${status}\\n" "${_message}"
  if [[ ${mode} == 'status' ]]; then
    printf '\n'
  fi
}

function _spinner {
  case ${1} in
    start)
      tput civis
      i=1
      while true; do
          _display_message "${_spinner_cycle:i++%${#_spinner_cycle}:1}" 'spinning'
          sleep ${_spinner_period}
        done
      ;;

    stop)
      tput cvvis
      if [[ -z ${_spinner_pid} ]]; then
          return 1
      fi
      kill "${_spinner_pid}" > /dev/null 2>&1
      if [[ ${2} == 0 ]]; then
        status="${GREEN}${SUCCESS}${RESET}"
      else
        status="${GREEN}${FAIL}${RESET}"
      fi
      _display_message ${status} 'status'
      ;;

    *)
      printf 'ERROR: invalid argument, try {start/stop}' &>2
      exit 2
      ;;
  esac
}

function start_spinner() {
  if [[ ${-} == *x* ]]; then
    return
  fi
  _message="${1}"
  _display_message
  _spinner 'start' &
  _spinner_pid="${!}"
  disown
}

function stop_spinner() {
  if [[ ${-} == *x* ]]; then
    return
  fi
  _spinner 'stop' "${1}"
  unset _spinner_pid
}

# Traps
for t in HUP INT QUIT KILL TERM EXIT; do
  trap "\
    return_code=\${?}
    trap - EXIT
    stop_spinner \${return_code}
    printf \"${t} %s\\n\" \"\${return_code}\" 1>&2
    exit \${return_code}
  " ${t}
done
