#!/bin/bash

# Copyright (C) 2018-2019 Andrei Pavel, andrei.pavel@cti.pub.ro
# Licensed under the MIT License

# Source guard
[[ -n "${_LIB_TRAPS_SOURCED+x}" ]] && return 0
export _LIB_TRAPS_SOURCED=true

# Traps
# Accounts for spinner as well
function traps() {
  local on_trap=
  if (( ${#} > 0 )); then
    on_trap=${1}
  fi
  for t in HUP INT QUIT KILL TERM EXIT; do
    trap "\
      return_code=\${?}
      trap - EXIT
      declare -f stop-spinner &> /dev/null && stop-spinner \${return_code}
      ${on_trap}
      printf \"${t} %s\\n\" \"\${return_code}\" 1>&2
      exit \${return_code}
    " "${t}"
  done
}
export -f traps

# Default traps
traps
