#!/bin/bash

# Copyright (C) 2017-2018 Andrei Pavel, andrei.pavel@cti.pub.ro
# Licensed under the MIT License

mandatory() {
  while (( ${#} > 0 )); do
    if [[ -z ${!1} ]]; then
      printf "%s argument is mandatory.\n" "${argument}" >&2
      printUsage
      exit 2
    fi
    shift
  done
}
